@WebApi_HostAddress = https://localhost:7189 

POST https://localhost:7189/api/tasks
Content-Type: application/json

{
  "title": "Сделать проект",
  "description": "Закончить сервисы и контроллеры",
  "dueDate": "2025-10-10"
}

###

GET https://localhost:7189/api/tasks
Accept: application/json

###

DELETE https://localhost:7189/api/Tasks/b4dfbf72-f4ad-4f40-a24d-efff18811818

###

POST  https://localhost:7189/api/auth/register
Content-Type: application/json

{
  "username": "LurkeR",
  "password": "19092006"
}

###

POST https://localhost:7189/api/Auth/login 
Content-Type: application/json

{
  "username": "LurkeR",
  "password": "19092006"
}

> {% client.global.set("accessToken", response.body.accessToken); %}

### 

GET https://localhost:7189/api/Tasks/me
Authorization: Bearer {{accessToken}}

### 

POST https://localhost:7189/api/auth/refresh


